### ISSUE TITLE
BUG: TVL for Leverage Bot is incorrect for $1,5000 USDC to leverage 0.0302 BTC

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1275]
Transaction hash: https://etherscan.io/tx/0x88b14a2c19626d5b416ad61cae8dfca6b802e5655647003337ddbc263e737dd3

TVL Total: $45.17 is not the value of the collateral which is $1,494.99

![Image](https://github.com/VolumeFi/paloma/assets/701864/cd60d9d3-2330-4ada-a013-cd5c730afd87)

**Comment by taariq** [comment]
@jamie088 where in the back end code do you acquire the TVL number?

**Comment by jamie088** [comment]
@taariq @rootedbox No, I have never worked for the TVL number in the backend. When want to get only the bots of a selected user, I added Curve leverage bot to the mybots API because only curve leverage bot was missed from mybots api.
in this api endpoints:
https://service.palomabot.ai/robots?depositor=0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432
https://service.palomabot.ai/robots?depositor=0x8F5eBDdcf2bae86D3A4E3C4De427E705d2eBF432&completed=true

**Comment by verabehr** [comment]
The FE uses to calculate TVL is `deposit_price`*`amount`

deposit_price and tracking_price in api are incorrect
`deposit_price`:"1495.8591298077429", `tracking_price`:"1559.0244703179726"
This is the tBTC and price is too low: https://www.coingecko.com/en/coins/tbtc

**Comment by jamie088** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/363. But not tested yet while updating the api.

**Comment by taariq** [comment]
@jamie088 this continues to be wrong: Are you sure your formula is correct. @rootedbox updated the TVL number today with https://github.com/VolumeFi/palomabot/pull/368

![Image](https://github.com/VolumeFi/paloma/assets/701864/ce0de9e9-1271-4ac2-9f2d-04528b56191a)

**Comment by taariq** [comment]
@rootedbox: notes from @jamie088 

1. coin_info0 of the Curve leverage bot (Collateral token) was missed from api result and needs to be fixed
2. The following are still not updated: 
  a. deposit_price and tracking_price "deposit_price":"1495.8591298077429","tracking_price":"1574.4534803565612"

**Comment by taariq** [comment]
Fixed with https://github.com/VolumeFi/palomabot/pull/369#event-11810603918
