### ISSUE TITLE
BUG: Mixpanel missing bot events

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#866]
1. The last `DB create` event happened one month ago, since then we only have `DB complete` events https://mixpanel.com/project/2744781/view/3280621/app/events#rSXEDJ48Yyr3
2. We are missing some `DB complete` events from this contract (and potentially others) https://etherscan.io/address/0x8C629A57eE1610581EB375529d07b097673d3470#events - there were 3 or so withdraw events today, but we have no `DB complete` events today. See this one for example https://etherscan.io/tx/0x07cb3cad6c5ac8c1dab16a97e63eb425a0a9aef6511e6a0594504e9b67ee1205
3. We are missing all `DB Complete` events from this contract  (and potentially others) https://bscscan.com/address/0xEE6aB4E4917A31F9085f7E7E5912e43B5E22D172

**Comment by rootedbox** [comment]
@verabehr The issues is with fees. I need to know how to calculate fees for lending bots.. this should fix all of this plus 860..

**Comment by verabehr** [comment]
service fee: on deposit (BotStarted): 0.3%

gas fee: when the contract is called via the script (repay or add_collateral): 0.015ETH

**Comment by rootedbox** [comment]
I think these should all be fixed now.. I will do qa on these in the morning @verabehr

**Comment by verabehr** [comment]
1. there are more events now, so potentially fixed
2. Still missing some - e.g. [0x122e231f62f421521ced929f07c535f4d3cceda926957bf34f49324f081076ee](https://etherscan.io/tx/0x122e231f62f421521ced929f07c535f4d3cceda926957bf34f49324f081076ee)
3. Still missing this contract

**Comment by rootedbox** [comment]
we are missing 0x07cb3cad6c5ac8c1dab16a97e63eb425a0a9aef6511e6a0594504e9b67ee1205 in our db. but every other transaction listed seems to be good. @verabehr

**Comment by verabehr** [comment]
This is still not fixed - reopening
